services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: yourUsername
      POSTGRES_PASSWORD: yourPassword
      POSTGRES_DB: banking
    ports:
      - "5432:5432"